version: "3"
services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - "80:80"
    volumes:
      - .:/var/www/exchange-rate
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: exchange-rate-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2346:2346"
    volumes:
      - .:/var/www/exchange-rate
